spring:
  application:
    name: organice-gateway

  cloud:
    discovery:
      locator:
        enabled: true
    gateway:
      routes:
        - id: organice-auth
          uri: lb://organice-auth
          predicates:
            - Path=/auth/**

        - id: organice-account
          uri: lb://organice-account
          predicates:
            - Path=/accounts/**
        
        - id: organice-lembrete
          uri: lb://organice-lembrete
          predicates:
            - Path=/lembretes/**

        - id: organice-dia
          uri: lb://organice-dia
          predicates:
            - Path=/dia/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

api:
  endpoints:
    open: >
        POST /auth/register,
        POST /auth/login,
        POST /lembretes/data,
        ANY /accounts/v3/api-docs,
        ANY /accounts/swagger-ui.html,
        ANY /auth/v3/api-docs,
        ANY /auth/swagger-ui.html,
        ANY /lembretes/v3/api-docs,
        ANY /lembretes/swagger-ui.html,
        ANY /dia/v3/api-docs,
        ANY /dia/swagger-ui.html,
        ANY /auth/actuator/**,
        ANY /accounts/actuator/**,
        ANY /lembretes/actuator/**,
        ANY /dia/actuator/**

management:
  endpoints:
    web:
      base-path: /gateway/actuator
      exposure:
        include: [ 'prometheus' ]
